### ISSUE TITLE
The example for pipe is not working

### ISSUE THREAD

**Issue by NomikOS** [logdna/tail-file-node#15]
I was able to run it this way:

```js
#!/usr/bin/env node
const stackdriver = require('pino-stackdriver')
const credentials = './foo.json'
const projectId = 'bar'
const writeStream = stackdriver.createWriteStream({ credentials, projectId })

const TailFile = require('@logdna/tail-file')
const tail = new TailFile('./logger.js.log')

;(async () => {
  try {
    await tail.start()
    tail.pipe(writeStream)

    tail.on('tail_error', (err) => {
      console.error('TailFile had an error!', err)
      throw err
    })
  } catch (err) {
    console.error('Cannot start.  Does the file exist?', err)
  }
})()

```

**Comment by darinspivey** [comment]
Ha, of course the pseudocode means that this was the only example we didn't test for real.  The problem is there's too much chaining off the constructor.  Your approach is fine too since there's a multitude of ways to wire it up.

The example will work if the constructor is allowed to return and assign the value to `tail`.  We'll get a fix up (along with an actual linesplitter like `split2`) shortly.  Thank you for pointing this out!

```javascript
const tail = new TailFile('./logfile.txt')
tail
  .on('tail_error', (err) => {
 // ...snip/...
```
