### ISSUE TITLE
Continue after application restart

### ISSUE THREAD

**Issue by tukusejssirs** [logdna/tail-file-node#19]
Sorry if this is a dumb question, but I need to continue watching the file tail for changes even when my app using `tail-file-node` would be restarted.

Currently we use some BASH scripts and [`logtail`](https://salsa.debian.org/debian/logcheck/-/blob/master/src/logtail) to get the changes from some logs. `logtail` creates offset and delta files which it can read when we run `logtail` next time.

We are about to port are app into Node JS (preferably TypeScript in the long run), therefore we are examining if `tail-file-node` will suit our needs.

As far as I understand it right, we can send the start position using `startPos` option, but how can we retrieve the _current_ start position in order to save it on our end and pass it when the app restarts / starts again?

---

To be more precise, what we want to do is the following:
1. We have log file on a MS Windows client computer which we copy once a minute to a Linux server.
2. `tail-file-node` would watch for changes the file on the Linux server and then our app would process the log.
3. However, this is part of monitoring of the client computer and we need to make sure that the monitoring could be safely turned on and off anytime, and when it starts, `tail-file-node` would continue watching the file where it stopped.
4. Also the Linux server could be restarted.

---

Thanks in advance! :wink:

**Comment by darinspivey** [comment]
This is actually a good feature request to report the internal offsets/state during runtime.  I actually figured this was coming as an addition, so you're certainly right to bring it up.

The brute force way to see the last "position" is to just check the size of the file.  Since tailing should always be caught up, that size in bytes would be the place where you'd pick up reading.  Can you answer some questions about your implementation? 

1. Which side initiates the copy?  Does the linux server pull the file from Windows, or the other way around? This would speak to your ability to control the flow of the tail and gather the file size before copying the latest file over to linux.
2. To clarify, is `tail-file-node` integrated with your `app` ?  The way you describe it somewhat sounds like they're 2 different things, although typical implementations would have the `app` and `tail-file` be 1 thing.
3. How often is tail-file restarting?  Again, this can be clarified by the second question.

In short, `tail-file` can only be given a `startPos` during instantiation.  If this is how your implementation works, then ok, but it almost sounds like you have a long-running app (and tail?).  I can envision this flow as a linux server running an app that watches for changes to a file, and when detected, fast-forward to the last-known position and keep reading.  However, that approach won't currently work since the tail is already running, but that could be fixed.

**Proposed enhancements:**
* Add a `state` event that will provide the state of tail file's pointers like last known `kStartPos`.  The preference would be to report this information and let it be consumed and written to wherever (file, database, in-memory object) rather than force file creation on the users. Writing this as a JSON object to a file, for example, would be ~5 lines of code.

* Potentially (depending on the answer of whether the tail is being killed/restarted) add a runtime "setter" for `startPos` such that it can be reset during execution.  Since copying a file will change the inode, this means the *entire* file would be re-read from the beginning.  So, if the desire is only to pick up the delta, then `startPos` could be changed on-the-fly after a `renamed` event is emitted

**Comment by tukusejssirs** [comment]
> 1. Which side initiates the copy?  Does the linux server pull the file from Windows, or the other way around? This would speak to your ability to control the flow of the tail and gather the file size before copying the latest file over to linux.

Server side. Simply put, the client (Windows) does not even know we use those logs. :wink:

> 2. To clarify, is `tail-file-node` integrated with your `app` ?  The way you describe it somewhat sounds like they're 2 different things, although typical implementations would have the `app` and `tail-file` be 1 thing.

Yes, `tail-file-node` will be integrated into our app once we solve #19 and #21.

The reason why I describe it as two different things is that from my point of view we use `tail-file-node` to do what we want it do, but yes, technically we integrate it into our app and from the end-user point of view it is the same thing. :wink:

> 3. How often is tail-file restarting?  Again, this can be clarified by the second question.

This is hard to answer.

We do CNC machines monitoring. The end-user can start or stop the monitoring on any machine individually anytime they want, but that said it should not happen quite often (they want the data gathered ideally for indefinite amount of time), but it could happen e.g. when the machine is out of service or being repaired. You might say that we might keep monitor the file on the server (which obviously would/should not change), but I think that it is not the right way to do.

Also the ethernet cables might get disconnected (by accident or intentionally).

And there is also a potentional server reboot, which is the main reason for this issue. I don’t think it is a good idea to keep the copied logs laying around (I think about them as temporarily needed files). I could read from the database (where we put the processed log data) and based on this info set the `startPos`.

> In short, `tail-file` can only be given a `startPos` during instantiation. If this is how your implementation works, then ok, but it almost sounds like you have a long-running app (and tail?). I can envision this flow as a linux server running an app that watches for changes to a file, and when detected, fast-forward to the last-known position and keep reading. However, that approach won't currently work since the tail is already running, but that could be fixed.

I see. I am thinking about an option to kill/destroy/stop `tail-file` running based on some (let’s say) callback function which we could create to check if a particular machine is currently to be monitored (and also if it is online); it would be run in a preconfigured interval and when the function decided that `tail-file` should be stopped or restarted, then it would do so.

> **Proposed enhancements:**
> 
> * Add a `state` event that will provide the state of tail file's pointers like last known `kStartPos`.  The preference would be to report this information and let it be consumed and written to wherever (file, database, in-memory object) rather than force file creation on the users. Writing this as a JSON object to a file, for example, would be ~5 lines of code.

I am for this. I would prefer to use the in-memory (returned) object that I could process. And I think that it might be a good idea to provide it as a second argument to the `data` event.

> * Potentially (depending on the answer of whether the tail is being killed/restarted) add a runtime "setter" for `startPos` such that it can be reset during execution.  Since copying a file will change the inode, this means the _entire_ file would be re-read from the beginning.  So, if the desire is only to pick up the delta, then `startPos` could be changed on-the-fly after a `renamed` event is emitted

This sounds good to me.

**Comment by darinspivey** [comment]
> I am thinking about an option to kill/destroy/stop tail-file running based on some (let’s say) callback function which we could create to check if a particular machine is currently to be monitored (and also if it is online); it would be run in a preconfigured interval and when the function decided that tail-file should be stopped or restarted, then it would do so.

I see.  I'd say that you'd only have to stop tailing if there was no longer a log file to tail.  Even though we could add a `tail.setPos`, that could introduce race conditions with the current read timers and copying the new file and trying to reset the position.  As long as we're on the same page about the proposed features, I suppose we don't need to fully understand how you'll use it.  That being said:

* We can't add `state` information as a second event parameter because the the `data` event belongs to the stream implementation and would only emit the data itself.  Therefore, it will have to be a separate event, but that wouldn't stop you from changing in-memory objects and/or flushing it to a file with a few lines of code (open a FH, which is continually truncated and re-written with `JSON.stringify(state)`)

* Adding a setter for the position is probably not a good idea, but your flow could look something like this:

```js
const fileName = 'SOMELOG.txt'
let tail = new TailFile(fileName)

if (fileNeedsToBe copied) {
  await tail.quit()
  // copy new file from windows to local linux server now
  tail = new TailFile(fileName, {startPos: lastKnownReadPos})
  tail.start() // etc
}
```

**Comment by tukusejssirs** [comment]
> * We can't add `state` information as a second event parameter because the the `data` event belongs to the stream implementation and would only emit the data itself.  Therefore, it will have to be a separate event, but that wouldn't stop you from changing in-memory objects and/or flushing it to a file with a few lines of code (open a FH, which is continually truncated and re-written with `JSON.stringify(state)`)

All of your previous comments looks good to me, but this section.

While understand the _`data` event belongs to the stream implementation and would only emit the data itself_, there might a race condition between the `data` and the `state` events (i.e. which comes first). I mean I’d like to get the last _processed_ position, that is _after_I process the data, I’d save the current `startPos` (`state`), not before or during it.

**Comment by darinspivey** [comment]
That's a fair point, but I'm not sure that's possible.  As you know, the stream can be consumed separately from when `tail-file` reads the files.  There probably isn't a clean way to tie the file position to any particular line in the stream since this is just following node stream implementation rules.

That problem might not need to be solved, though.  If there are new log files coming in, it would seem that current tail stream can be exhausted before starting a new tail, and that's the recommendation.  In other words, `await once(tail, 'flush')` prior to closing the tail.  At that point, we could have a feature that reports the last read position because at that point, the consumption and last position would be in sync.  We could still add the `state` event, and perhaps that would fire *after* `flush` is emitted, and also after `.quit()`, keeping everything in sync.  Thoughts?

**Comment by tukusejssirs** [comment]
You’re right. However, what about the case when the logging gets interrupted during the day (when the log might be appended into the same file)? When I restart the app, `tail-file` needs to know where to start (i.e. continue) in order to make sure that no line (1) is processed twice; (2) skipped.

**Comment by darinspivey** [comment]
Ah, it's hard to speak intelligently about your specific use case, namely 'when the log might be appended into the same file', but when something dies or is killed, there is always the chance for data loss.  That can't be avoided here.  However, if it's firing a `state` event after each `flush`, then a "best approach" could be to capture that into a file that could be loaded upon restart.  Worst case scenario is that the position would be slightly behind if it was killed 

Here's a remedial example:

```js
const FH = await fs.promises.open('statefile.txt')

tail.on('state', (state) => {
  FH.writeFile(JSON.stringify(state)).catch((err) => {
    // log error or something
  })
})

process.on('SIGTERM', () => {
  FH.close().catch(() => {})
})
```

If you think adding this `state` event after a `flush` is helpful, then we're happy to make this a feature request.

**Comment by tukusejssirs** [comment]
@darinspivey, thanks for all your help! :+1:

> If you think adding this `state` event after a `flush` is helpful, then we're happy to make this a feature request.

I do think it would be very useful. Thanks! :wink:

**Comment by darinspivey** [comment]
As it turns out, the `flush` event did not previously have a payload.  Rather than creating a new event that needs to be fired after `flush`, we will add the `startPos` as a property of the flush event payload.  PR incoming.
