### ISSUE TITLE
Cannot quit() tailFile instance after storing in an array of object

### ISSUE THREAD

**Issue by frufin** [logdna/tail-file-node#31]
As i need to tail mutiple files, each new tailFile is stored inside an array of objects:
```
const tail = new TailFile(filename, { encoding: 'utf8' })
        .on('data', chunk => {...})
        ...
        .start()

tailsArray.push({
        filename: filename,
        tail: tail
      })
```

In such a case, trying to quit() returns the error:  'quit() is not a function' when i try this:
```
const myTail = tailsArray.find(t => t.filename == myFilename)
myTail.tail.quit()
```

Any error referencing the tailFIle object before storing ?

**Comment by mdeltito** [comment]
Hi @frufin 

Looking at the snippet you provided, the problem is that you are assigning `tail` to the return value of `.start()`:

```js
const tail = new TailFile(filename, opts).start()
```

However, `start()` [does not return a reference](https://github.com/logdna/tail-file-node/blob/9c452c65931e10ec08dd04ec3b22d7f54dca6ab7/lib/tail-file.js#L112) to the instance (`this`) to allow this form of chaining which is why you are getting that error.

Instead you can separate the statements when creating the `tail` instance, and it should work as you expect:

```js
// first create the instance
const tail = new TailFile(filename, {encoding: 'utf8'})

// then attach the handler
tail.on('data', (chunk) => { ... })

// then start() - note that this is an async function, ideally you would be handling 
// it as a promise or with `await`
tail.start()

tailsArray.push({
  filename: filename,
  tail: tail // this is now a proper reference to the instance
})
// and so on
```

An enhancement here might be to allow chaining so that your original version works the same way. cc: @darinspivey for thoughts/opinions there

Hope this helps!

**Comment by frufin** [comment]
@darinspivey thanks for your reply !
I have indeed found that referencing tail before applying the start function solves this problem.
Your answer explains that not chaining was the problem...

**Comment by darinspivey** [comment]
We can certainly return `this` from the `start` function--there's no reason this wasn't done except for not having a valid use case :]

It is a little tricky due to what @mdeltito pointed about about best practice being to `await start()` since it can/will throw an error for things like "file not found."  To do that in your example, you'd want to chain a thenable in order to catch it.  There's no real reason to not return `this` other than potential confusion if users forget to catch that error.  We're happy to add that as an enhancement if you wanna open an Issue.  Thanks for your feedback!

If we made that change, your code could become something like this

```js
const tail = new TailFile(filename, { encoding: 'utf8' })
        .on('data', chunk => {...})
        ...
        .start()
        .catch((err) => {
          process.nextTick(() => {
            const error = new Error(`Cannot start tailing ${filename}: ${err}`)
            throw error
          })
        })

```
